# Generated by Django 4.2.7 on 2025-11-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_rename_aitivo_banner_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
