# Generated by Django 5.2.7 on 2025-11-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenspedidos',
            old_name='pedids',
            new_name='pedidos',
        ),
    ]
