# Generated by Django 5.2.7 on 2025-11-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rename_pedids_itenspedidos_pedidos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItensPedidos',
            new_name='ItensPedido',
        ),
    ]
