# Generated by Django 5.2.7 on 2025-11-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='aitivo',
            new_name='ativo',
        ),
    ]
